# Generated by Django 3.2.20 on 2023-10-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lx_pathway_plugin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pathway',
        ),
    ]
